// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lazyman.vansing.domain;

import com.lazyman.vansing.domain.Grade;
import com.lazyman.vansing.domain.GradeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GradeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GradeDataOnDemand: @Component;
    
    private Random GradeDataOnDemand.rnd = new SecureRandom();
    
    private List<Grade> GradeDataOnDemand.data;
    
    public Grade GradeDataOnDemand.getNewTransientGrade(int index) {
        Grade obj = new Grade();
        setName(obj, index);
        return obj;
    }
    
    public void GradeDataOnDemand.setName(Grade obj, int index) {
        String name = "name_" + index;
        if (name.length() > 10) {
            name = name.substring(0, 10);
        }
        obj.setName(name);
    }
    
    public Grade GradeDataOnDemand.getSpecificGrade(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Grade obj = data.get(index);
        Long id = obj.getId();
        return Grade.findGrade(id);
    }
    
    public Grade GradeDataOnDemand.getRandomGrade() {
        init();
        Grade obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Grade.findGrade(id);
    }
    
    public boolean GradeDataOnDemand.modifyGrade(Grade obj) {
        return false;
    }
    
    public void GradeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Grade.findGradeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Grade' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Grade>();
        for (int i = 0; i < 10; i++) {
            Grade obj = getNewTransientGrade(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
