// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lazyman.vansing.domain;

import com.lazyman.vansing.domain.PaymentDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PaymentDataOnDemand_Roo_Configurable {
    
    declare @type: PaymentDataOnDemand: @Configurable;
    
}
