// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lazyman.vansing.domain;

import com.lazyman.vansing.domain.Teacher;
import com.lazyman.vansing.domain.TeacherDataOnDemand;
import com.lazyman.vansing.domain.TeacherIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TeacherIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TeacherIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TeacherIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TeacherIntegrationTest: @Transactional;
    
    @Autowired
    TeacherDataOnDemand TeacherIntegrationTest.dod;
    
    @Test
    public void TeacherIntegrationTest.testCountTeachers() {
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", dod.getRandomTeacher());
        long count = Teacher.countTeachers();
        Assert.assertTrue("Counter for 'Teacher' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TeacherIntegrationTest.testFindTeacher() {
        Teacher obj = dod.getRandomTeacher();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to provide an identifier", id);
        obj = Teacher.findTeacher(id);
        Assert.assertNotNull("Find method for 'Teacher' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Teacher' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TeacherIntegrationTest.testFindAllTeachers() {
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", dod.getRandomTeacher());
        long count = Teacher.countTeachers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Teacher', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Teacher> result = Teacher.findAllTeachers();
        Assert.assertNotNull("Find all method for 'Teacher' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Teacher' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TeacherIntegrationTest.testFindTeacherEntries() {
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", dod.getRandomTeacher());
        long count = Teacher.countTeachers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Teacher> result = Teacher.findTeacherEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Teacher' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Teacher' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TeacherIntegrationTest.testFlush() {
        Teacher obj = dod.getRandomTeacher();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to provide an identifier", id);
        obj = Teacher.findTeacher(id);
        Assert.assertNotNull("Find method for 'Teacher' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTeacher(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Teacher' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TeacherIntegrationTest.testMergeUpdate() {
        Teacher obj = dod.getRandomTeacher();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to provide an identifier", id);
        obj = Teacher.findTeacher(id);
        boolean modified =  dod.modifyTeacher(obj);
        Integer currentVersion = obj.getVersion();
        Teacher merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Teacher' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TeacherIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", dod.getRandomTeacher());
        Teacher obj = dod.getNewTransientTeacher(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Teacher' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Teacher' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Teacher' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TeacherIntegrationTest.testRemove() {
        Teacher obj = dod.getRandomTeacher();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Teacher' failed to provide an identifier", id);
        obj = Teacher.findTeacher(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Teacher' with identifier '" + id + "'", Teacher.findTeacher(id));
    }
    
}
