// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lazyman.vansing.domain;

import com.lazyman.vansing.domain.Teacher;
import com.lazyman.vansing.domain.TeacherDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect TeacherDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TeacherDataOnDemand: @Component;
    
    private Random TeacherDataOnDemand.rnd = new SecureRandom();
    
    private List<Teacher> TeacherDataOnDemand.data;
    
    public Teacher TeacherDataOnDemand.getNewTransientTeacher(int index) {
        Teacher obj = new Teacher();
        setMemo(obj, index);
        setName(obj, index);
        setPhoneNumber(obj, index);
        return obj;
    }
    
    public void TeacherDataOnDemand.setMemo(Teacher obj, int index) {
        String memo = "memo_" + index;
        if (memo.length() > 60) {
            memo = memo.substring(0, 60);
        }
        obj.setMemo(memo);
    }
    
    public void TeacherDataOnDemand.setName(Teacher obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public void TeacherDataOnDemand.setPhoneNumber(Teacher obj, int index) {
        String phoneNumber = "phoneNumber_" + index;
        if (phoneNumber.length() > 20) {
            phoneNumber = phoneNumber.substring(0, 20);
        }
        obj.setPhoneNumber(phoneNumber);
    }
    
    public Teacher TeacherDataOnDemand.getSpecificTeacher(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Teacher obj = data.get(index);
        Long id = obj.getId();
        return Teacher.findTeacher(id);
    }
    
    public Teacher TeacherDataOnDemand.getRandomTeacher() {
        init();
        Teacher obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Teacher.findTeacher(id);
    }
    
    public boolean TeacherDataOnDemand.modifyTeacher(Teacher obj) {
        return false;
    }
    
    public void TeacherDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Teacher.findTeacherEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Teacher' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Teacher>();
        for (int i = 0; i < 10; i++) {
            Teacher obj = getNewTransientTeacher(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
