// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lazyman.vansing.domain;

import com.lazyman.vansing.domain.School;

privileged aspect School_Roo_JavaBean {
    
    public String School.getName() {
        return this.name;
    }
    
    public void School.setName(String name) {
        this.name = name;
    }
    
}
